name: Run benchmarks

on:
  pull_request:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.3
      - name: Install dependencies
        run: julia -e 'using Pkg; pkg"add JSON PkgBenchmark BenchmarkCI@0.1"'
      - name: Run benchmarks
        run: julia benchmark/run_benchmarks.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
